language: node_js
node_js:
   - 0.6


env: DB=couchdb

before_script:
  - curl -X PUT localhost:5984/myapp_test
  - npm install kanso -g
  - npm install nodeunit -g

notifications:
  email:
    - ryan.ramage@gmail.com
    - mw@data.io
    - caolan.mcmahon@gmail.com

script: "kanso install; kanso push http://localhost:5984/myapp_test"